#!/usr/bin/env python

import sys

from rqt_file_dialog.file_dialog import RqtFileDialog
from rqt_gui.main import Main

plugin = 'rqt_file_dialog'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
